[branches]
base = "main"
release = "release"

[tags]
chore = "Chores"
feat = "New Features"
fix = "Bug Fixes"
perf = "Performance Improvements"
refactor = "Refactors"

[packages.fomalhaut]
path = "crates/fomalhaut"
resolver = "rust"
channel = "alpha"

[packages.fomalhaut-core]
path = "crates/fomalhaut-core"
resolver = "rust"
channel = "alpha"

[packages.fomalhaut-sdk]
path = "packages/fomalhaut-sdk"
resolver = "nodejs"
channel = "alpha"

[packages.fomalhaut-session]
path = "crates/fomalhaut-session"
resolver = "rust"
channel = "alpha"

[packages.fomalhaut-web]
path = "crates/fomalhaut-web"
resolver = "rust"
channel = "alpha"

[resolver.rust.pre-check]
type = "http"
url = "https://crates.io/api/v1/crates/{{ package.name }}/{{ package.version }}"

[resolver.rust.pre-check.extra-headers]
User-Agent = "Semifold 0.3.0-beta.1"

[[resolver.rust.publish]]
command = "cargo"
args = ["publish"]

[[resolver.rust.post-version]]
command = "cargo"
args = [
    "generate-lockfile",
]
dry-run = true

[resolver.nodejs.pre-check]
type = "http"
url = "https://registry.npmjs.org/{{ package.name }}/{{ package.version }}"

[[resolver.nodejs.publish]]
command = "npm"
args = [
    "publish",
    "--provenance",
    "--access",
    "public",
    "--tag",
    "alpha",
]
