[package]
name = "fomalhaut"
edition = "2024"
version = "0.1.0-alpha"
description = "WebKitGTK display manager greeter for greetd"
license.workspace = true
repository.workspace = true

[dependencies]
fomalhaut-core = { version = "0.1.0-alpha", path = "../fomalhaut-core" }
fomalhaut-session = { version = "0.1.0-alpha", path = "../fomalhaut-session" }
fomalhaut-web = { version = "0.1.0-alpha", path = "../fomalhaut-web" }
gtk4 = "0.11.4"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["net", "rt"] }
toml = "1.1.4"
webkit6 = { version = "0.6.1", features = ["gtk_v4_18"] }

[lints]
workspace = true

[dev-dependencies]
greetd_ipc = { version = "0.10.3", features = ["tokio-codec"] }
