[package]
name = "fomalhaut-web"
edition = "2024"
version = "0.1.0-alpha.3"
description = "Frontend protocol, theme loader, and web greeter controller for Fomalhaut"
license.workspace = true
repository.workspace = true

[dependencies]
cap-std = "4.0.2"
fomalhaut-core = { version = "0.1.0-alpha.2", path = "../fomalhaut-core" }
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.4"
ts-rs = { version = "12.0.1", features = ["no-serde-warnings"] }
zeroize = "1.9.0"

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt"] }
