[package]
name = "fomalhaut-web"
edition = "2024"
version = "0.1.0-alpha"
license.workspace = true

[dependencies]
fomalhaut-core = { version = "0.1.0-alpha", path = "../fomalhaut-core" }
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
zeroize = "1.9.0"

[lints]
workspace = true
