[package]
name = "fomalhaut-config"
version = "0.1.0-alpha.2"
edition = "2024"
description = "Shared strict configuration for Fomalhaut greeter and locker"
license.workspace = true
repository.workspace = true

[dependencies]
fomalhaut-session = { version = "0.1.0-alpha.1", path = "../fomalhaut-session" }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.4"

[lints]
workspace = true
