[package]
name = "fomalhaut-lock"
version = "0.1.0-alpha.2"
edition = "2024"
description = "Wayland session locker with a WebKitGTK interface for Fomalhaut"
license.workspace = true
repository.workspace = true

[dependencies]
fomalhaut-config = { version = "0.1.0-alpha.2", path = "../fomalhaut-config" }
fomalhaut-core = { version = "0.1.0-alpha.2", path = "../fomalhaut-core" }
fomalhaut-gtk = { version = "0.1.0-alpha.0", path = "../fomalhaut-gtk" }
fomalhaut-logind = { version = "0.1.0-alpha.0", path = "../fomalhaut-logind" }
fomalhaut-pam = { version = "0.1.0-alpha.0", path = "../fomalhaut-pam" }
fomalhaut-user = { version = "0.1.0-alpha.0", path = "../fomalhaut-user" }
fomalhaut-web = { version = "0.1.0-alpha.4", path = "../fomalhaut-web" }
gtk4 = "0.11.4"
gtk4-session-lock = { version = "=0.4.0", features = ["v1_2"] }
tokio = { version = "1.53.1", features = ["rt"] }

[lints]
workspace = true
