[package]
name = "fomalhaut-gtk"
version = "0.1.0-alpha.0"
edition = "2024"
description = "Shared GTK4 and WebKitGTK host infrastructure for Fomalhaut"
license.workspace = true
repository.workspace = true

[dependencies]
fomalhaut-web = { version = "0.1.0-alpha.2", path = "../fomalhaut-web" }
gtk4 = "0.11.4"
webkit6 = { version = "0.6.1", features = ["gtk_v4_18"] }

[lints]
workspace = true
